### ISSUE TITLE
Listening on shared queues

### ISSUE THREAD

**Issue by andymurd** [fvinas/multi_sqs_listener#1]
It would be great to include support for SQS queues owned by another AWS account.

The [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.get_queue_url) indicate that `QueueOwnerAWSAccountId` needs to be supplied to `get_queue_url()` for this to work.

Without that parameter, I'm seeing an exception:
`botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist for this wsdl version.`

**Comment by fvinas** [comment]
Feature merged with with PR #2, thank you for your contribution! ✅
